// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>

#include <NEPODefs.h>



std::list<double> ___item;
std::list<bool> ___item2;
std::list<String> ___item3;
std::list<unsigned int> ___item4;
int _led_L = 13;
void setup()
{
    Serial.begin(9600);
    pinMode(_led_L, OUTPUT);
    ___item = {0, 0, 0, 0};
    ___item2 = {true, false, true, false, true, false, false, true};
    ___item3 = {"a", "b", "c", "b"};
    ___item4 = {RGB(0xff, 0xcc, 0x33), RGB(0xff, 0xff, 0x33), RGB(0x66, 0x00, 0x00), RGB(0x00, 0x00, 0x99), RGB(0x66, 0x33, 0xff), RGB(0xff, 0x99, 0x00)};
}

void loop()
{
    Serial.println(_getListElementByIndex(_getSubList(___item, 0, 2), 0));
    Serial.println(_getListElementByIndex(_getSubList(___item2, 0, 2), 0));
    Serial.println(_getListElementByIndex(_getSubList(___item3, 0, 2), 0));
    Serial.println(_getListElementByIndex(_getSubList(___item4, 0, 2), 0));
    Serial.println(_getAndRemoveListElementByIndex(_getSubList(___item, 0, 2), 0));
    Serial.println(_getAndRemoveListElementByIndex(_getSubList(___item2, 0, 2), 0));
    Serial.println(_getAndRemoveListElementByIndex(_getSubList(___item3, 0, 2), 0));
    Serial.println(_getAndRemoveListElementByIndex(_getSubList(___item4, 0, 2), 0));
    _removeListElementByIndex(_getSubList(___item, 0, 2), 0);
    _removeListElementByIndex(_getSubList(___item2, 0, 2), 0);
    _removeListElementByIndex(_getSubList(___item3, 0, 2), 0);
    _removeListElementByIndex(_getSubList(___item4, 0, 2), 0);
    _setListElementByIndex(_getSubList(___item, 1, 2), 1, 256);
    _setListElementByIndex(_getSubList(___item2, 1, 2), 1, true);
    _setListElementByIndex(_getSubList(___item3, 1, 2), 1, "b");
    _setListElementByIndex(_getSubList(___item4, 1, 2), 1, RGB(0x66, 0x00, 0x00));
    Serial.println(((int) _getSubList(___item, 0, 2).size()));
    Serial.println(_getFirstOccuranceOfElement(_getSubList(___item4, 2, 4), RGB(0x00, 0x00, 0x99)));
    Serial.println(_getFirstOccuranceOfElement(_getSubList(___item3, 2, 4), String("b")));
    Serial.println(_getFirstOccuranceOfElement(_getSubList(___item2, 2, 4), true));
    Serial.println(_getFirstOccuranceOfElement(_getSubList(___item, 2, 4), 0));
    _insertListElementBeforeIndex(_getSubList(___item4, 1, 2), 1, RGB(0x66, 0x00, 0x00));
    _insertListElementBeforeIndex(_getSubList(___item3, 1, 2), 1, "b");
    _insertListElementBeforeIndex(_getSubList(___item2, 1, 2), 1, true);
    _insertListElementBeforeIndex(_getSubList(___item, 1, 2), 1, 0);
    delay(1000);
}
