// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>

#include <NEPODefs.h>


unsigned int ___red;
unsigned int ___green;
unsigned int ___blue;
int _led_L = 13;
int _led_red_R = 6;
int _led_green_R = 5;
int _led_blue_R = 3;
void setup()
{
    pinMode(_led_L, OUTPUT);
    pinMode(_led_red_R, OUTPUT);
    pinMode(_led_green_R, OUTPUT);
    pinMode(_led_blue_R, OUTPUT);
    ___red = RGB(255, 0, 0);
    ___green = RGB(0, 255, 0);
    ___blue = RGB(0, 0, 255);
}

void loop()
{
    analogWrite(_led_red_R, RCHANNEL(___red));
    analogWrite(_led_green_R, GCHANNEL(___red));
    analogWrite(_led_blue_R, BCHANNEL(___red));
    
    delay(500);
    analogWrite(_led_red_R, RCHANNEL(___green));
    analogWrite(_led_green_R, GCHANNEL(___green));
    analogWrite(_led_blue_R, BCHANNEL(___green));
    
    delay(500);
    analogWrite(_led_red_R, RCHANNEL(___blue));
    analogWrite(_led_green_R, GCHANNEL(___blue));
    analogWrite(_led_blue_R, BCHANNEL(___blue));
    
    delay(500);
    analogWrite(_led_red_R, RCHANNEL(___green));
    analogWrite(_led_green_R, GCHANNEL(___green));
    analogWrite(_led_blue_R, BCHANNEL(___green));
    
    delay(500);
}